// Objective-C API for talking to github.com/hajimehoshi/ebiten/mobile/ebitenmobileview Go package.
//   gobind -lang=objc github.com/hajimehoshi/ebiten/mobile/ebitenmobileview
//
// File is generated by gobind. Do not edit.

#include <Foundation/Foundation.h>
//#include "seq.h"
//#include "_cgo_export.h"
#include "Ebitenmobileview.objc.h"


#ifdef __cplusplus
extern "C" {
#endif


extern void proxyebitenmobileview__Layout(double p0, double p1);

extern void proxyebitenmobileview__Resume();

// skipped function SetGame with unsupported parameter or result types

extern void proxyebitenmobileview__SetUIView(int64_t p0);

extern void proxyebitenmobileview__Suspend();

extern int32_t proxyebitenmobileview__Update();

extern void proxyebitenmobileview__UpdateTouchesOnAndroid(int p0, int p1, int p2, int p3);

extern void proxyebitenmobileview__UpdateTouchesOnIOS(int p0, int64_t p1, int p2, int p3);

extern void proxymobile__Dummy();

#ifdef __cplusplus
}
#endif


void EbitenmobileviewLayout(double viewWidth, double viewHeight) {
	double _viewWidth = (double)viewWidth;
	double _viewHeight = (double)viewHeight;
	proxyebitenmobileview__Layout(_viewWidth, _viewHeight);
}

void EbitenmobileviewResume(void) {
	proxyebitenmobileview__Resume();
}

// skipped function SetGame with unsupported parameter or return types

void EbitenmobileviewSetUIView(int64_t uiview) {
	int64_t _uiview = (int64_t)uiview;
	proxyebitenmobileview__SetUIView(_uiview);
}

void EbitenmobileviewSuspend(void) {
	proxyebitenmobileview__Suspend();
}

BOOL EbitenmobileviewUpdate(NSError* _Nullable* _Nullable error) {
	int32_t r0 = proxyebitenmobileview__Update();
	//Universeerror* _error = nil;
	//GoSeqRef* _error_ref = go_seq_from_refnum(r0);
	//if (_error_ref != NULL) {
	//  _error = _error_ref.obj;
	//  if (_error == nil) {
	//    _error = [[Universeerror alloc] initWithRef:_error_ref];
	//  }
	//}
	//if (_error != nil && error != nil) {
	//  *error = _error;
	//}
	return YES;
}

void EbitenmobileviewUpdateTouchesOnAndroid(long action, long id_, long x, long y) {
	//nint _action = (nint)action;
	//nint _id_ = (nint)id_;
	//nint _x = (nint)x;
	//nint _y = (nint)y;
	proxyebitenmobileview__UpdateTouchesOnAndroid(action, id_, x, y);
}

void EbitenmobileviewUpdateTouchesOnIOS(long phase, int64_t ptr, long x, long y) {
	//nint _phase = (nint)phase;
	//int64_t _ptr = (int64_t)ptr;
	//nint _x = (nint)x;
	//nint _y = (nint)y;
	proxyebitenmobileview__UpdateTouchesOnIOS(phase, ptr, x, y);
}

__attribute__((constructor)) static void init() {
	//init_seq();
}
