// Objective-C API for talking to github.com/hajimehoshi/ebiten/mobile/ebitenmobileview Go package.
//   gobind -lang=objc github.com/hajimehoshi/ebiten/mobile/ebitenmobileview
//
// File is generated by gobind. Do not edit.

#include <Foundation/Foundation.h>
#include "seq.h"
#include "_cgo_export.h"
#include "Ebitenmobileview.objc.h"


void EbitenmobileviewLayout(double viewWidth, double viewHeight) {
	double _viewWidth = (double)viewWidth;
	double _viewHeight = (double)viewHeight;
	proxyebitenmobileview__Layout(_viewWidth, _viewHeight);
}

void EbitenmobileviewResume(void) {
	proxyebitenmobileview__Resume();
}

// skipped function SetGame with unsupported parameter or return types

void EbitenmobileviewSetUIView(int64_t uiview) {
	int64_t _uiview = (int64_t)uiview;
	proxyebitenmobileview__SetUIView(_uiview);
}

void EbitenmobileviewSuspend(void) {
	proxyebitenmobileview__Suspend();
}

BOOL EbitenmobileviewUpdate(NSError* _Nullable* _Nullable error) {
	int32_t r0 = proxyebitenmobileview__Update();
	Universeerror* _error = nil;
	GoSeqRef* _error_ref = go_seq_from_refnum(r0);
	if (_error_ref != NULL) {
		_error = _error_ref.obj;
		if (_error == nil) {
			_error = [[Universeerror alloc] initWithRef:_error_ref];
		}
	}
	if (_error != nil && error != nil) {
		*error = _error;
	}
	return (_error == nil);
}

void EbitenmobileviewUpdateTouchesOnAndroid(long action, long id_, long x, long y) {
	nint _action = (nint)action;
	nint _id_ = (nint)id_;
	nint _x = (nint)x;
	nint _y = (nint)y;
	proxyebitenmobileview__UpdateTouchesOnAndroid(_action, _id_, _x, _y);
}

void EbitenmobileviewUpdateTouchesOnIOS(long phase, int64_t ptr, long x, long y) {
	nint _phase = (nint)phase;
	int64_t _ptr = (int64_t)ptr;
	nint _x = (nint)x;
	nint _y = (nint)y;
	proxyebitenmobileview__UpdateTouchesOnIOS(_phase, _ptr, _x, _y);
}

__attribute__((constructor)) static void init() {
	init_seq();
}
