// Objective-C API for talking to github.com/hajimehoshi/ebiten/mobile/ebitenmobileview Go package.
//   gobind -lang=objc github.com/hajimehoshi/ebiten/mobile/ebitenmobileview
//
// File is generated by gobind. Do not edit.

#ifndef __GO_ebitenmobileview_H__
#define __GO_ebitenmobileview_H__

#include <stdint.h>
#include <objc/objc.h>
#endif
