// Code generated by gobind. DO NOT EDIT.

// Package main is an autogenerated binder stub for package mobile.
//
//   autogenerated by gobind -lang=go github.com/nikki93/ebiten-test/mobile
package main

/*
#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "mobile.h"

*/
import "C"

import (
	"github.com/nikki93/ebiten-test/mobile"
	_seq "golang.org/x/mobile/bind/seq"
)

// suppress the error if seq ends up unused
var _ = _seq.FromRefNum

//export proxymobile__Dummy
func proxymobile__Dummy() {
	mobile.Dummy()
}
