// Objective-C API for talking to github.com/nikki93/ebiten-test/mobile Go package.
//   gobind -lang=objc github.com/nikki93/ebiten-test/mobile
//
// File is generated by gobind. Do not edit.

#include <Foundation/Foundation.h>
#include "seq.h"
#include "_cgo_export.h"
#include "Mobile.objc.h"


void MobileDummy(void) {
	proxymobile__Dummy();
}

__attribute__((constructor)) static void init() {
	init_seq();
}
