// Objective-C API for talking to github.com/nikki93/ebiten-test/mobile Go package.
//   gobind -lang=objc github.com/nikki93/ebiten-test/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __GO_mobile_H__
#define __GO_mobile_H__

#include <stdint.h>
//#include <objc/objc.h>
#endif
